---
prometheus_version: 2.27.1
nodeexporter_version: 1.1.2
os_arch: linux-amd64
retention_time: 60d
retention_size: 40GB
prometheus_url: monitoring.mentorship.local
targets:
        - {name: job-name, url: 'domain.com', username: xxx, password: xxx}
